### ISSUE TITLE
Modify css for code section

### ISSUE THREAD

**Issue by titipata** [tupleblog/tupleblog.github.io#10]
@bluenex, I think we should change the css for code section to make it looks better.

**Comment by bluenex** [comment]
Oh I forgot about this already. How should we make the change? any rough idea?

To me, font size should be increased a bit and maybe change font too?

**Comment by titipata** [comment]
So I'd like code section to be in different font instead. It should be easier to read on laptop also. Right now the position of code chunk is a little tight.

**Comment by bluenex** [comment]
Monospace font should be good as a coding font. Please check this (Google font)[https://fonts.google.com/?category=Monospace] and pick some for testing.

For me **Roboto Mono**, **Inconsolata** and **Overpass Mono** look good.

**Comment by titipata** [comment]
+1 for **Roboto Mono**! Should we also put the code chunk in light grey background, same as in-line code snippet?

**Comment by titipata** [comment]
@bluenex found this [page](https://github.com/dwayne/sass-pygments/tree/master/styles/scss) for `scss` file. We can use it for new light-grey color background.

**Comment by bluenex** [comment]
This was done in e7f7439ba00ba627e2977b9ae7ad64939d7d384e.
