### ISSUE TITLE
minor fix

### ISSUE THREAD

**Issue by bluenex** [tupleblog/tupleblog.github.io#2]
- [x] change all tupleblog word to be TupleBlog
- [x] add `by` in front of author name in mobile view of post page
- [x] increasing font size in `about` banner
- [x] make menu button always fixed at top left and disappear after no moving for a while
- [x] do something with `continue reading` word (cut it out!)
- [x] add `date-time` and `author` to post-index in __mobile view__

**Comment by bluenex** [comment]
- move 'continue reading' to next line
- add date-tim+author to post-index in mobile view
- may add break to post-index so that we will use continue reading for every articles

**Comment by titipata** [comment]
I think TupleBlog is good. Others bullet are good to change too

**Comment by bluenex** [comment]
for `make menu button always fixed at top left and disappear after no moving for a while`

can't automatically disappear yet, but is moved to top right and show all time in stead.
